name: Code Formatting Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  black-format-check:
    name: Check Python code formatting with Black
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        cache: 'pip'
    
    - name: Install Black
      run: |
        python -m pip install --upgrade pip
        pip install black
    
    - name: Check code formatting with Black
      run: |
        echo "Checking Python code formatting with Black..."
        black --check --diff .